### ISSUE TITLE
Tab for World of Coding

### ISSUE THREAD

**Issue by Nick67644** [mhxion/awesome-discord-communities#101]
# World of Coding
- World of Coding is one of the largest programming/infosec help servers on the discord platform with over 10,000 messages daily and currently 31,000 members from all walks of life!
     -  Discord partner!
     -  Server age: 3 years
     -  We are also the official server for the r/code subreddit!

# Why World of Coding
- With some of the best support out there we have a staff team working around the clock helping users who join, welcoming them into the server and setting them up for success in all terms. We offer help for anything you can think of when it comes to programming/tech (Assuming its legal/follows tos).

# Search for Devs!
- We have channels where you can show off your Creations!
Well, what if I am looking for a dev? We have for that too if you are looking for a dev, we have channels to search for some!
This also means you can find channels to advertise your services!

# Weekly Coding events!
* We host weekly coding events and planning on hosting more! 🎉 
* ❓We host major AMAs with companies and other servers!
* Our event server has 2k members which is used for bot jams and hackathons! ⚔️ 
     - Servers involved in these events hosted by World of Coding include Fireship, TCR, Disnake, Pycord, D++, and many other dev communities!
     
# Info
- 🌐 Need help with programming? We got it!
- 💻 OS systems, Networking, Databases, Hosting, Frameworks and more!
- 💰 Cryptocurrency talk
- 💾 Channel for compiling your code! 
- 🔑 Cryptography
- 🔒 Cyber Security

Website:  https://world-of-coding.tech/

🔗 ➥Invite link
https://discord.gg/program

☁️ ➥Weather bot! (Our custom weather bot!)
https://world-of-coding.tech/weather

**Comment by mhxion** [comment]
Hi @Nick67644. Thanks for your request. I will review the server soon. (Sorry for late response!)

**Comment by mhxion** [comment]
PR in #102.
