### ISSUE TITLE
Discord Development Section

### ISSUE THREAD

**Issue by Lulalaby** [mhxion/awesome-discord-communities#104]
The reddit wiki linked there is outdated since years.
Instead https://libs.advaith.io/ should be linked.

Advaiths list was recently updated with all known information and is a way better source to determine what to use due to the overview of major feature implementations.

**Comment by mhxion** [comment]
I think I will add "https://libs.advaith.io/ " as a resource as well. Thanks!

**Comment by Lulalaby** [comment]
I totally forgot about that 😂

**Comment by mhxion** [comment]
> I totally forgot about that 😂

Just got back to working on this awesome list 😅

**Comment by mhxion** [comment]
Merged with [95cd762](https://github.com/mhxion/awesome-discord-communities/commit/95cd7623dd1cf3d339fbff9b8cb4d8bef8c75932)
