### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by MKS1699** [mhxion/awesome-discord-communities#105]
CS Career Hackers

Invite Link is INVALID.

![Screenshot from 2023-04-21 16-14-49](https://user-images.githubusercontent.com/50589853/233617269-c2421271-a0fd-4912-a961-7b1b8b359bfd.png)

current Link  : [https://discord.com/invite/rGwhXJv](https://discord.com/invite/rGwhXJv)

This is the current valid link 
[https://discord.com/invite/ndFR4RF](https://discord.com/invite/ndFR4RF)
I found of the group via [`reddit`](https://www.reddit.com/r/cscareerquestions/comments/a7y8qg/cs_career_hackers_discord_server/)

**Comment by mhxion** [comment]
Thanks for reporting. Fixed with #115.
