### ISSUE TITLE
CS Career Hackers invalid invite

### ISSUE THREAD

**Issue by Jewelry-x** [mhxion/awesome-discord-communities#107]
**Community name that is currently listed:**
CS Career Hackers

**Describe the issue:**
Server got renamed to CS Career Hub, and the invite link is expired.

**Expected:**
Here is the new link: https://discord.gg/ndFR4RF. Not sure if renaming the server is also required.

**Additional context:**
https://www.reddit.com/r/cscareerquestions/comments/a7y8qg/cs_career_hackers_discord_server/

**Comment by mhxion** [comment]
Hello, thank you for bringing it up. I will be looking into the renamed server, and fix it soon. Feel free to make PR if you wish to fix it yourself as well :)

**Comment by mhxion** [comment]
Fixed with #115.

**Comment by mhxion** [comment]
Duplicate of #99.
