### ISSUE TITLE
Raspberry Pi link is no longer valid

### ISSUE THREAD

**Issue by JonThomas801** [mhxion/awesome-discord-communities#109]
**Community name that is currently listed:**
Raspberry Pi

Here is the link to the "Raspberry Pie" Discord server: https://discord.com/invite/raspberry-pie-204621105720328193

**Comment by mhxion** [comment]
Hi @JonThomas801. Thanks for reporting. I will fix it soon.

**Comment by mhxion** [comment]
Fixed. Thanks for reporting.
