### ISSUE TITLE
Toxic community

### ISSUE THREAD

**Issue by ghost** [mhxion/awesome-discord-communities#113]
**Community name that is currently listed:**
Discord-Linux

**Describe the issue:**
Is there an invite link that is invalid, or notable channels need to be updated?

The community is not that accepting of people who may use other distributions and is known to argue often, which discourages users. For example, a user posted that they loved arch Linux because in their words 'it is bleeding edge and good looking' to which 2 of the active members started arguing with them over how Arch is just a terminal and that any distro is better than the hell that is 'arch'. Another user was talking with the arch enjoyer, saying how arch is a very good learning tool for Linux and that it is akin to a uni course. 

The other members then started arguing with them over how arch does not teach anyone how Linux works and that you're better off using anything else (because no other distro installs like arch?). The argument quickly devolved when a member said that the arch user was 'strawmaning' because they said that no other distro has a handbook/wiki like Arch to guide you through the instillation. Upon which the arch user told them they are toxic and to 'get some #####' and were then promptly banned. 

I do not talk much in the server as I joined out of curiosity but I often see how they argue with new users and the like over nitpicky things until the other person gets frustrated and banned. I worry that such a community is hurting the Linux community and at least should not be listed as a recommendation here, or frankly anywhere.  Frequently do new users get greeted with 'just google it' or 'read how x works' when they ask how to fix an issue, they even ban people who go to DMs to help people which may use Linux Mint, because according to their rules such distros are banned and they do not allow DM support.

**Expected:**
What do you want to replace the community with regarding the aforementioned issue? 

I recommend that the community is removed from the list and in the future a more suitable one added, the other Linux discords are completely fine and succinct.

**Additional context:**

None

**Comment by mhxion** [comment]
Hi @alexxsandar52, thank you for a detailed report. I have been in a hiatus from this small project, hence the late response. I have done a quick review of "Discord Linux" server, and went through their `#mod-logs`.

> For example, a user posted that they loved arch Linux because in their words 'it is bleeding edge and good looking' to which 2 of the active members started arguing....
> The argument quickly devolved when a member said that the arch user was 'strawmaning' because they said that no other distro has a handbook/wiki like Arch to guide you through the instillation. Upon which the arch user told them they are toxic and to 'get some #####' and were then promptly banned.

I am not sure how I can consider the server toxic when the user got banned after posting "get some #####" . Though, in such case, I personally would not probably give a permanent ban, but this doesn't immediately justify toxicity within the server.

> ... but I often see how they argue with new users and the like over nitpicky things until the other person gets frustrated and banned. 

I am not sure if you mean new users get constantly bullied which would be a allowing toxic attitudes. Ideally, this would require a case-by-case review. 

> Frequently do new users get greeted with 'just google it' or 'read how x works'

After searching for "google it", I failed to get a sufficient number of messages that would justify this claim. Or maybe I just missed them. They do seem to provide dedicated support channels: `#support-linux`. 

> they even ban people who go to DMs to help people which may use Linux Mint, because according to their rules such distros are banned and they do not allow DM support.

This is a fairly common rule that you see in many servers. This rule is mainly there to fight spam DMs. The ban would not be justified, if the said banned user was DM-ing another with their permission. I.e., the server mods shouldn't care what two members do in their DMs with consent. 


### Further remarks

I have contacted one of the moderators of the server, and they were cooperative in helping me review your report. They pointed me to the first case you brought up here (about Arch). After reviewing the message, I believe that case alone doesn't justify toxicity as there was a violation of server rules from banned user. I do not mean to say whether the ban was justified or not, that's not within my purview. I **do not** think I have found anything so far that would deem the server as toxic so as to be removed from this awesome list. But maybe I wasn't thorough enough in my review, so I will remain open to other user reports of course. In the meantime, I will consider this issue as completed.

**Comment by mhxion** [comment]
It seems user account has been deleted.
![Screenshot 2024-08-07 at 4 34 07 PM](https://github.com/user-attachments/assets/2356ba3c-740d-4339-85ec-e0917810fbc8)

 Closing this issue.
