### ISSUE TITLE
Python 

### ISSUE THREAD

**Issue by white371** [mhxion/awesome-discord-communities#16]

**Comment by mhxion** [comment]
@white371 Can you describe the issue? There doesn't seem to be anything wrong with Python communities.

**Comment by Secret158** [comment]
;)

**Comment by Secret158** [comment]
;)

**Comment by Secret158** [comment]
Hy ;)

**Comment by Secret158** [comment]
Sorry i speak German and Hungary


Gesendet von Yahoo Mail für iPhone


Am Samstag, Juli 4, 2020, 10:23 AM schrieb Mahadi Xion <notifications@github.com>:




@white371 Can you describe the issue? There doesn't seem to be anything wrong with Python communities.

**Comment by mhxion** [comment]
Sie haben mir keine Details zu Ihrem Problem gegeben. Können Sie weitere Informationen geben?

**Comment by mhxion** [comment]
I'm closing this issue due to no response from the author.

**Comment by Secret158** [comment]
https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees
