### ISSUE TITLE
Add "back to top" link at the end of every section.

### ISSUE THREAD

**Issue by JoseDeFreitas** [mhxion/awesome-discord-communities#17]
With the table of contents, you can easily search for what you're looking for. You can also use the `alt/⌘ + left arrow` to go back to the previous section and search using the word search `ctrl + f`.
This is a good method, but I tried going to the table of contents again and I had to use the scrollbar. It's not a big deal using it, but since you have the cursor hovering over the list, you have to move the cursor to the scrollbar and then drag it to the top.
It will be easier if you had a "Back to top" button at the end of each section (just the sections, not sub-sections).
The button could be something like `⬆ back to top`, linking to the table of contents (`Contents`).
This is a minimum recommendation and it doesn't affect reality, but it's just a recommendation I think it could be better in my opinion, while I was navigating through the list.

**Comment by mhxion** [comment]
The list grew a lot since its onset, it does makes sense to have this navigational option. I'll be working on this 🙂

**Comment by Rodrigo001-de** [comment]
Ok

Em sáb, 4 de jul de 2020 19:25, Mahadi Xion <notifications@github.com>
escreveu:

**Comment by dkaiser014** [comment]
Hi! is someone working on this? i wouldn't mind doing it

**Comment by JoseDeFreitas** [comment]
Hello @dkaiser014. I think no one is working on this, so it'd be a nice contribution. Though let's wait for mhxion to decide whether to do it or not (as I see this issue was added to the milestone "Smooth Exploration").

**Comment by mhxion** [comment]
@dkaiser014 Hello, thanks for your interest. I'll start working on it soon, I'll likely adopt the navigation style from [best-of](https://github.com/best-of-lists/best-of), I like their simple `^` icon. I have got a few more communities to wrap up. If you still want to work on it, feel free to do so, you can show your navigation styles by opening up a draft PR, and we can discuss there.

**Comment by dkaiser014** [comment]
I checked out the navigation style from [best-of](https://github.com/best-of-lists/best-of) and it's pretty clean, I like it, I'll open a PR asap, thanks :smile:
