### ISSUE TITLE
Raylib game development community

### ISSUE THREAD

**Issue by Airbus5717** [mhxion/awesome-discord-communities#30]
**Community name that is currently listed:**

**Describe the issue:**
Is there an invite link that is invalid, or notable channels need to be updated?

https://discord.gg/mzCY3wN

**Expected:**
What do you want to replace the community with regarding the aforementioned issue? 

**Additional context:**
raylib is a simple and easy-to-use library to enjoy videogames programming.

**Comment by mhxion** [comment]
@Airbus5717 Sorry for late. I had to wrap up a few things. Just added this community in [game development tools](https://github.com/mhxion/awesome-discord-communities#game-development-tools) (`ced8958`)(https://github.com/mhxion/awesome-discord-communities/commit/ced895858b5a157e111cff9e8b411641b37bab0f)
