### ISSUE TITLE
[BUG] Alignment of Logos

### ISSUE THREAD

**Issue by Akshu-on-github** [mhxion/awesome-discord-communities#37]
The `Homelab` community's logo is not in order with the rest of the logos

<p align="center"><img src="https://user-images.githubusercontent.com/61582763/101772777-d4774080-3b11-11eb-8b67-636207b21c25.png" height = 200px></p>

**Comment by mhxion** [comment]
Thanks for submitting this @Akshu-on-github. Commit [1eebc8e5](https://github.com/mhxion/awesome-discord-communities/commit/1eebc8e5486198292a73eee247ec3b433286873f) should have fixed this issue.
