### ISSUE TITLE
Kotlin Discord server

### ISSUE THREAD

**Issue by Airbus5717** [mhxion/awesome-discord-communities#52]
There are 2 Kotlin servers atm

https://discord.gg/gjXqqCS

Together Kotlin is run by Together Java mods [edited]
https://discord.gg/j7TkSPD3mb

**Comment by GrayThinker** [comment]
Second link has expired

**Comment by Airbus5717** [comment]
ah here is a new one 
https://discord.gg/j7TkSPD3mb

**Comment by Secret158** [comment]
https://discord.gg/j7TkSPD3mb

**Comment by Secret158** [comment]
Hy everybody

**Comment by Secret158** [comment]
Hello

**Comment by Secret158** [comment]
https://discord.gg/j7TkSPD3mb

**Comment by Secret158** [comment]
[Creator]() 
![img1618343648129](https://user-images.githubusercontent.com/67779481/116951492-5108e800-ac88-11eb-9c4d-62b454e4c349.jpg)

**Comment by Secret158** [comment]
> There are 2 Kotlin servers atm
> 
> https://discord.gg/gjXqqCS
> 
> Together Kotlin is run by Together Java mods [edited]
> https://discord.gg/j7TkSPD3mb

**Comment by Secret158** [comment]
Wtf?
