### ISSUE TITLE
Code::Together invite has expired

### ISSUE THREAD

**Issue by crxssed7** [mhxion/awesome-discord-communities#60]
**Community name that is currently listed:**
Code::Together

**Describe the issue:**
Invite link has expired

**Expected:**
What do you want to replace the community with regarding the aforementioned issue? - Replace invite link with a new one, preferably a never expiring one

**Comment by m0lese** [comment]
4d4c891

**Comment by aayushsrivastava9760** [comment]
I m still unable to join via link .

**Comment by m0lese** [comment]
> I m still unable to join via link .

Check (https://github.com/mhxion/awesome-discord-communities/pull/67/commits/dc572657a995ff7005f607771201e8d85c5720b3)

**Comment by aayushsrivastava9760** [comment]
Yes, thnx this link works

**Comment by UltiRequiem** [comment]
dont works anymore

**Comment by m0lese** [comment]
@UltiRequiem Check (dc57265)

**Comment by Keyacom** [comment]
I suspect the server is closed because the website and repo have also been taken down.

**Comment by mhxion** [comment]
Fixed. Thanks for reporting.
